# Name of website
title: 麻瓜担保 - 全球首家数字货币第三方担保交易平台

# Short description of your site
description: 麻瓜担保致力于解决网络交易中，买卖双方付款交货的的信任问题。让网络交易更安全，让骗子无机可乘公平公正第三方数字货币担保交易平台。

# url is the the website domain URL without a trailing slash
#url: "https://danbao.mugglepay.com"
